server:
  port: 8090

spring:
  application:
    name: School-Service
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/micro_service
    username: root
    password: Hellgaze@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8282/eureka/
  instance:
    hostname: localhost
